del /S /A *.ncb
del /S /A *.suo
del /S /A *.user
del /S /A *.htm
del /S /A *.dep
del /S /A *.exp
del /S /A *.obj
del /S /A *.pdb
del /S /A *.idb
del /S /A *.manifest
del /S /A *.ilk
del /S /A *.manifest.res
del /S /A *.pch
del /S /A *.resources
del /S /A *.Cache
del /S /A *.user
del /S /A *.txt
